version: "3.7"

services:
  app:
    image: node:20-alpine

    command: sh -c "npm install && npm run dev"

    ports:
      - $PORT:$PORT

    working_dir: /app

    volumes:
      - ./:/app

    environment:
      PORT: $PORT
      URL_MONGODB_DEV: $URL_MONGODB_DEV
      URL_MONGODB_PROD: $URL_MONGODB_PROD
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRATION: $JWT_EXPIRATION
      JWT_REFRESH_TOKEN_SECRET: $JWT_REFRESH_TOKEN_SECRET
      JWT_REFRESH_TOKEN_EXPIRATION: $JWT_REFRESH_TOKEN_EXPIRATION
      GMAIL: $GMAIL
      PASSWORD: $PASSWORD

    restart: always
